# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-06 06:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
